# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-04 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboardmodule',
            name='user',
            field=models.CharField(max_length=120, verbose_name='user'),
        ),
    ]
