# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-18 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jet', '0002_delete_userdashboardmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.CharField(max_length=120, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='pinnedapplication',
            name='user',
            field=models.CharField(max_length=120, verbose_name='user'),
        ),
    ]
